title: Garry's blog!
email: hellothere@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We will talk about gaming and awsome music! Are you ready to jump in?

# Social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
